#!/usr/bin/env bash
## Install web server - Nginx.
## -----------------------------
## Run sudo update.
sudo apt-get -y update
## Install nginx.
sudo apt-get -y install nginx
## Change User /var/www
sudo chown -R ubuntu /var/www
## Change file default --> index.html to nginx.
echo "Hello World!" > /var/www/html/index.nginx-debian.html
## Create file error --> error_404.html to nginx.
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
## Service nginx - start.
sudo service nginx start
## Redirecting to another page (The redirection must be a “301 Moved Permanently”)
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=NdYWuo9OFAw permanent;/" /etc/nginx/sites-available/default
## Redirecting to another page (The page must return an HTTP 404 error code)
sudo sed -i "s/^server\s{/server {\n\terror_page 404 \/error_404.html;/1" /etc/nginx/sites-available/default
## Service nginx - restart.
sudo service nginx restart
