#!/usr/bin/env bash
# This script displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration.
i=0
while  [ $i -lt 20 ]
do
	case $i in
		5) echo $"bad luck";;
		7) echo $"good luck";;
		18) echo $"Best School"
	esac
	echo $i
	((i=i+1))
done
