#!/usr/bin/env bash
# configures container to run Nginx as the nginx user
chown nginx:nginx /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/sites-available/default
chmod u+rwx /etc/nginx/nginx.conf
chmod u+rwx /etc/nginx/sites-available/default
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
pkill apache2
su nginx service nginx restart
