#!/usr/bin/env bash
#Run Nginx as Nginx
sudo pkill apache2
sudo pkill nginx
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
