#!/usr/bin/env bash
# configures container to run Nginx as the nginx user
chown nginx:nginx /etc/nginx/nginx.conf
chmod a+rwx /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
pkill apache2
su nginx service nginx restart
